django/core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    # General app's urls
    path('', include('mapping-community-groups.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/mapping-community-groups/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'mapping-community-groups'
urlpatterns = [
    path('', TemplateView.as_view(template_name="mapping-community-groups/coming-soon.html"), name='comingsoon'),
    path('cookies', TemplateView.as_view(template_name="mapping-community-groups/cookies.html"), name='cookies'),
]

django/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mapping Community Groups and "Common Ground" (Coming Soon)</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <main role="main">
        {% block content %}{% endblock %}
    </main>
    <footer role="contentinfo">
        <p>
            <a href="https://www.birmingham.ac.uk/privacy/index.aspx" target="_blank">Privacy</a> |
            <a href="https://www.birmingham.ac.uk/legal/index.aspx" target="_blank">Legal</a> |
            <a href="https://www.birmingham.ac.uk/university/governance/policies-regs/information/index.aspx" target="_blank">Freedom of Information</a> |
            <a href="{% url 'mapping-community-groups:cookies' %}">Cookies</a> |
            <a href="https://accessibility.bear.bham.ac.uk/" target="_blank">Accessibility</a>
        </p>
    </footer>
</body>
</html>

django/mapping-community-groups/templates/mapping-community-groups/coming-soon.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Coming Soon</h1>
<p>The <span class="highlight">Mapping Community Groups and "Common Ground"</span> website is under construction and will be coming soon.</p>
<p>For information about the project in the meantime, please email: <a href="mailto:bear-software@contacts.bham.ac.uk">bear-software@contacts.bham.ac.uk</a></p>
{% endblock %}

django/mapping-community-groups/templates/mapping-community-groups/comming-soon.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Coming Soon</h1>
<p>The <span class="highlight">Mapping Community Groups and "Common Ground"</span> website is under construction and will be coming soon.</p>
<p>For information about the project in the meantime, please email: <a href="mailto:bear-software@contacts.bham.ac.uk">bear-software@contacts.bham.ac.uk</a></p>
{% endblock %}

django/mapping-community-groups/templates/mapping-community-groups/cookies.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Cookies</h1>
<p>The Community Mapping website does not use cookies. For more information about cookies, including what they are and how you can manage them, please visit the University of Birmingham’s <a href="https://www.birmingham.ac.uk/privacy/cookies.aspx">cookies policy page</a>.</p>
{% endblock %}